### ISSUE TITLE
Some issue with WOTW 7.0.6

### ISSUE THREAD

**Issue by misaki44440** [dwallorde/War-of-the-Walkers-Mod-V7#8]
Hi, in first Good Job for your job. 

I have the latest WOTW 7.0.4 (clean install) and  in perk I miss one "icon" about Melee Weapon Craftink Perk. And if i click where we miss "icon" we have "Null ReferenceException:Object reference not set to an instance of an object"

Some bug with bottleWater, in firecamp if we try to made some bottlewater we see the recipe one with "icon" firecamp the 2nd nothing. only in firecamp needed i think.

Recyclable waste have no icon just a big point interrogation. 

And same pb than in discord write about vending machine, if you open ione bad you can't open all the other until you quit the game.

Good luck and thanks again, except that's I love your mod.

**Comment by dwallorde** [comment]
1.  Icon has been fixed for V7.0.5, though I never have had it cause a Nul Ref by clicking on it.  Test to see if this occurs in latest version
2.  Not really sure on what your saying.  If your seeing 2 recipes, one might be cheaper that is made at the Player Oven most likely
3.  What Recyclable Waste?  And what do you mean just a big point interrogation?  Could you screenshot that one for me?
4.  That should now be fixed in V7.0.5

**Comment by misaki44440** [comment]
Hi Dwallorde, sorry for later answer.

Use latest version of your mod v7.0.6

1) The "icon" is good but you still have some error when you mouse go in the right side bellow the "icon" in all this "page" where you have 0/0 for armor crafting perk or melee weapon crafting ... 

https://zupimages.net/viewer.php?id=20/14/cawf.jpg

2) the first bottlewater and the second is same .... the latest is different so ok, but for the two first is strange.

https://zupimages.net/viewer.php?id=20/14/fsph.jpg

3) I dont have with the latest update so it's ok.
